{% set data = load_setup_py_data() %}
{% set version = data.get('version') %}

# TODO review meta.yml spec and fill in missing fields as necessary (e.g. build number).
package:
  name: q2templates
  version: {{ version }}

source:
  path: ../..

build:
  script: make install

requirements:
  build:
    - python 3.5*
    - setuptools

  run:
    - python 3.5*
    - setuptools
    - jinja2

test:
  imports:
    - q2templates

about:
  home: https://qiime2.org
  license: BSD-3-Clause
  license_family: BSD
